name: CI - Feature Branches

on:
  push:
    branches-ignore:
      - main

jobs:
  test_unitarios:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Run unit tests only
        run: mvn clean test -Dtest=FilmServiceUnitTest

  test_integracion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Run integration tests only
        run: mvn clean verify -Dtest=FilmServiceIntegrationTest
